/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cinesation;

import Data.*;
import java.io.IOException;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rionna
 */
public class Report extends javax.swing.JFrame {
    public Employee emp;
    public MySQLConnector db;
    Data.TicketData td;
    Data.PurchaseData pd;

    /**
     * Creates new form Report
     */
    public Report(Employee e) throws SQLException {
        this.td = new TicketData();
        this.pd = new PurchaseData();
        initComponents();
        emp=e;
        db=new MySQLConnector();
        getCusttbl();
        getEmptbl();
        getMovietbl();
        getTickTypetbl();
        getScntbl();
        getSnacktbl();
        getSnackPurchtbl();
        getTicketPurchtbl();
        getReport1();
        getReport2();
        getReport3();
        getReport4();
        getReport5();
        getReport6();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCust = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMovie = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblTickType = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblScreening = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSnacks = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSnack_purch = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblReport1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblReport2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblReport3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblReport4 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblReport5 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblReport6 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(51, 255, 0));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(933, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tblCust.setBackground(new java.awt.Color(0, 0, 0));
        tblCust.setForeground(new java.awt.Color(51, 255, 0));
        tblCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Number", "Name", "Surname", "Date OF Birth", "Contact Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCust);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("Customers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        tblEmp.setBackground(new java.awt.Color(0, 0, 0));
        tblEmp.setForeground(new java.awt.Color(51, 255, 0));
        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Number", "Name", "Surname", "Is Manager", "Date Of Birth", "Contact Number", "Email"
            }
        ));
        jScrollPane2.setViewportView(tblEmp);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Employees");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Employee", jPanel2);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        tblMovie.setBackground(new java.awt.Color(0, 0, 0));
        tblMovie.setForeground(new java.awt.Color(51, 255, 0));
        tblMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Synopsis", "Genre", "Cast", "Duration In Minutes", "Director"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMovie.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblMovie.setCellSelectionEnabled(true);
        tblMovie.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMovieMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblMovie);
        tblMovie.getAccessibleContext().setAccessibleName("");
        tblMovie.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("Movies");

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtArea.setRows(5);
        jScrollPane3.setViewportView(txtArea);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("Movie Description");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Movie", jPanel4);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));

        tblTickType.setBackground(new java.awt.Color(0, 0, 0));
        tblTickType.setForeground(new java.awt.Color(51, 255, 0));
        tblTickType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ticket Type", "Ticket Price"
            }
        ));
        jScrollPane15.setViewportView(tblTickType);

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 0));
        jLabel15.setText("Ticket Type");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ticket Type", jPanel15);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        tblScreening.setBackground(new java.awt.Color(0, 0, 0));
        tblScreening.setForeground(new java.awt.Color(51, 255, 0));
        tblScreening.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Ticket Type", "Cinema", "Date", "Time"
            }
        ));
        jScrollPane6.setViewportView(tblScreening);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("Screenings");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Screening", jPanel6);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        tblSnacks.setBackground(new java.awt.Color(0, 0, 0));
        tblSnacks.setForeground(new java.awt.Color(51, 255, 0));
        tblSnacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Snack Name", "Snack Desc", "Snack Price"
            }
        ));
        jScrollPane5.setViewportView(tblSnacks);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 0));
        jLabel5.setText("Snacks");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Snack", jPanel5);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        tblSnack_purch.setBackground(new java.awt.Color(0, 0, 0));
        tblSnack_purch.setForeground(new java.awt.Color(51, 255, 0));
        tblSnack_purch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Employee ID", "Snack Name", "Quantity", "Amount (R)"
            }
        ));
        jScrollPane7.setViewportView(tblSnack_purch);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("Snack Purchases");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Snack Purchase", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        tblTickets.setBackground(new java.awt.Color(0, 0, 0));
        tblTickets.setForeground(new java.awt.Color(51, 255, 0));
        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Employee ID", "Purchase Date", "Movie Title", "Cinema", "Seat Row", "Seat Number", "Screening Date", "Screening Time", "Ticket Type", "Ticket Price"
            }
        ));
        jScrollPane8.setViewportView(tblTickets);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8.setText("Tickets");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ticket", jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        tblReport1.setBackground(new java.awt.Color(0, 0, 0));
        tblReport1.setForeground(new java.awt.Color(51, 255, 0));
        tblReport1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Points", "Number of Purchases", "Total Amount Spent (R)"
            }
        ));
        jScrollPane9.setViewportView(tblReport1);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("Customers and the total amount of money they spend");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report 1", jPanel9);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        tblReport2.setBackground(new java.awt.Color(0, 0, 0));
        tblReport2.setForeground(new java.awt.Color(51, 255, 0));
        tblReport2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Screening Time", "Number of Tickets Bought"
            }
        ));
        jScrollPane10.setViewportView(tblReport2);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 0));
        jLabel10.setText("Most Bought Movie Tickets And their Screening Time");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report 2", jPanel10);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        tblReport3.setBackground(new java.awt.Color(0, 0, 0));
        tblReport3.setForeground(new java.awt.Color(51, 255, 0));
        tblReport3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Movie Title", "Ticket Type", "Total Amount"
            }
        ));
        jScrollPane11.setViewportView(tblReport3);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 0));
        jLabel11.setText("Movie and Ticket Type that brought in the most Money");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report 3", jPanel11);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        tblReport4.setBackground(new java.awt.Color(0, 0, 0));
        tblReport4.setForeground(new java.awt.Color(51, 255, 0));
        tblReport4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee Surname", "Number of Purchase", "Total Amount"
            }
        ));
        jScrollPane12.setViewportView(tblReport4);

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 0));
        jLabel12.setText("Employees and the total Sales and Money From total Sales");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report 4", jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        tblReport5.setBackground(new java.awt.Color(0, 0, 0));
        tblReport5.setForeground(new java.awt.Color(51, 255, 0));
        tblReport5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Customer Surname", "Snack Name", "Quantity", "Total Amount (R)"
            }
        ));
        jScrollPane13.setViewportView(tblReport5);

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 0));
        jLabel13.setText("Total amount customers spends on each Snacks");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report 5", jPanel13);

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        tblReport6.setBackground(new java.awt.Color(0, 0, 0));
        tblReport6.setForeground(new java.awt.Color(51, 255, 0));
        tblReport6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Customer Surname", "Total Quantity", "Average Amount Spent on Snacks"
            }
        ));
        jScrollPane14.setViewportView(tblReport6);

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 0));
        jLabel14.setText("The Average Each customer spends on snacks");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report 6", jPanel14);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(51, 255, 0));
        jButton1.setText("Back To Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(51, 255, 0));
        jButton2.setText("Generate SQL Script For ticket and purchase");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(47, 47, 47)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            db.closeDB();
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        try {
            new MainMenu(emp).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            generateScript();
        } catch (IOException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMovieMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dT=(DefaultTableModel)tblMovie.getModel();
        txtArea.setText("");
        txtArea.append((String) dT.getValueAt(tblMovie.getSelectedRow(),1)+"\n");
        txtArea.append("\n"+"Cast:"+"\n");
        txtArea.append((String)dT.getValueAt(tblMovie.getSelectedRow(),3)+"\n");
        
    }//GEN-LAST:event_tblMovieMouseClicked

    /**
     * @param args the command line arguments
     * 
     */
    
    public void getCusttbl() throws SQLException{
      ResultSet rs=db.query("SELECT IDNumber, Name,Surname, Date_of_birth, ContactNumber, Email FROM person JOIN customer ON customer.cIDNumber=person.IDNumber");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblCust.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("IDNumber"));
              vect.add(rs.getString("Name"));
              vect.add(rs.getString("Surname"));
              vect.add(rs.getString("Date_of_birth"));
              vect.add(rs.getString("ContactNumber"));
              vect.add(rs.getString("Email"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getEmptbl() throws SQLException{
      ResultSet rs=db.query("SELECT IDNumber, Name,Surname, isManager, Date_of_birth, ContactNumber, Email FROM person JOIN employee ON employee.eIDNumber=person.IDNumber");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblEmp.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("IDNumber"));
              vect.add(rs.getString("Name"));
              vect.add(rs.getString("Surname"));
              vect.add(rs.getBoolean("isManager"));
              vect.add(rs.getString("Date_of_birth"));
              vect.add(rs.getString("ContactNumber"));
              vect.add(rs.getString("Email"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getMovietbl() throws SQLException{
      ResultSet rs=db.query("SELECT Title, Synopis, Genre, Cast, Duration, Director FROM movie");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblMovie.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("Title"));
              vect.add(rs.getString("Synopis"));
              vect.add(rs.getString("Genre"));
              vect.add(rs.getString("Cast"));
              vect.add(rs.getInt("Duration"));
              vect.add(rs.getString("Director"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getSnacktbl() throws SQLException{
      ResultSet rs=db.query("SELECT SnackName, SnackDisc, SnackPrice FROM snack");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblSnacks.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("SnackName"));
              vect.add(rs.getString("SnackDisc"));
              vect.add(rs.getFloat("SnackPrice"));
            
          }
          
          dT.addRow(vect);
     }
    }
    public void getTickTypetbl() throws SQLException{
      ResultSet rs=db.query("SELECT TicketType, TPrice From ticket_type");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblTickType.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("TicketType"));
              vect.add(rs.getFloat("TPrice"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getScntbl() throws SQLException{
      ResultSet rs=db.query("SELECT Title, TicketType, CinemaID, sDate, sTime FROM screening JOIN movie ON movie.MovieID=screening.movieID JOIN ticket_type ON screening.TicketTypeID=ticket_type.TicketTypeID ORDER BY sDate, sTime");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblScreening.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("Title"));
              vect.add(rs.getString("TicketType"));
              vect.add(rs.getInt("CinemaID"));
              vect.add(rs.getString("sDate"));
              vect.add(rs.getString("sTime"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getSnackPurchtbl() throws SQLException{
      ResultSet rs=db.query("SELECT cIDNumber, eIDNumber, SnackName, Quantity, (Quantity*SnackPrice) FROM snack_purchase JOIN snack ON snack.SnackID=snack_purchase.SnackID JOIN purchase ON purchase.PurchaseID=snack_purchase.PurchaseID ORDER BY  (Quantity*SnackPrice)");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblSnack_purch.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("cIDNumber"));
              vect.add(rs.getString("eIDNumber"));
              vect.add(rs.getString("SnackName"));
              vect.add(rs.getInt("Quantity"));
              vect.add(rs.getFloat("(Quantity*SnackPrice)"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getTicketPurchtbl() throws SQLException{
      ResultSet rs=db.query("SELECT cIDNumber, eIDNumber, pDate, Title, screening.CinemaID, SeatRow, SeatNumber, sDate, sTime, TicketType, TPrice FROM ticket JOIN screening ON screening.ScreeningID=ticket.ScreeningID JOIN movie ON movie.movieID=screening.MovieID JOIN ticket_type ON ticket_type.TicketTypeID=screening.TicketTypeID JOIN purchase ON purchase.PurchaseID=ticket.PurchaseID JOIN seat ON ticket.SeatID=seat.SeatID ORDER BY pDate");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblTickets.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("cIDNumber"));
              vect.add(rs.getString("eIDNumber"));
              vect.add(rs.getString("pDate"));
              vect.add(rs.getString("Title"));
              vect.add(rs.getInt("screening.CinemaID"));
              vect.add(rs.getString("SeatRow"));
              vect.add(rs.getInt("SeatNumber"));
              vect.add(rs.getString("sDate"));
              vect.add(rs.getString("sTime"));
              vect.add(rs.getString("TicketType"));
              vect.add(rs.getInt("TPrice"));
              
              
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getReport1() throws SQLException{
      ResultSet rs=db.query("SELECT name, surname, points, COUNT(PurchaseID),SUM(TotalCost) FROM person JOIN customer ON customer.cIDNumber=person.IDNumber JOIN purchase ON customer.cIDNumber=purchase.cIDNumber GROUP BY customer.cIDNumber ORDER BY SUM(TotalCost) DESC");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblReport1.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("name"));
              vect.add(rs.getString("surname"));
              vect.add(rs.getInt("points"));
              vect.add(rs.getInt("COUNT(PurchaseID)"));
              vect.add(rs.getFloat("SUM(TotalCost)"));;
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getReport2() throws SQLException{
      ResultSet rs=db.query("SELECT Title, sTime, Count(TicketID) FROM movie LEFT JOIN screening ON screening.movieID=movie.MovieID LEFT JOIN ticket ON ticket.ScreeningID=screening.ScreeningID GROUP BY movie.MovieID, sTime ORDER BY Count(TicketID) DESC");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblReport2.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("Title"));
              vect.add(rs.getString("sTime"));
              vect.add(rs.getInt("Count(TicketID)"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getReport3() throws SQLException{
      ResultSet rs=db.query("SELECT Title, TicketType, Count(TicketID)*TPrice FROM movie LEFT JOIN screening ON screening.movieID=movie.MovieID LEFT JOIN ticket ON ticket.ScreeningID=screening.ScreeningID LEFT JOIN ticket_type ON screening.TicketTypeID=ticket_type.TicketTypeID GROUP BY movie.MovieID, ticket_type.TicketTypeID ORDER BY Count(TicketID)*TPrice DESC");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblReport3.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("Title"));
              vect.add(rs.getString("TicketType"));
              vect.add(rs.getFloat("Count(TicketID)*TPrice"));
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getReport4() throws SQLException{
      ResultSet rs=db.query(" SELECT name, surname, COUNT(PurchaseID), SUM(TotalCost) FROM person JOIN employee ON employee.eIDNumber=person.IDNumber JOIN purchase ON employee.eIDNumber=purchase.eIDNumber GROUP BY employee.eIDNumber ORDER BY SUM(TotalCost) DESC");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblReport4.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("name"));
              vect.add(rs.getString("surname"));
              vect.add(rs.getInt("COUNT(PurchaseID)"));
              vect.add(rs.getFloat("SUM(TotalCost)"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getReport5() throws SQLException{
      ResultSet rs=db.query("SELECT name, surname, SnackName, Quantity, SUM(Quantity*SnackPrice) FROM person JOIN customer ON customer.cIDNumber=person.IDNumber JOIN purchase ON customer.cIDNumber=purchase.cIDNumber JOIN snack_purchase ON snack_purchase.PurchaseID=purchase.PurchaseID JOIN snack ON snack.SnackID=snack_purchase.SnackID GROUP BY purchase.cIDNumber, snack.SnackID ORDER BY SUM(Quantity*SnackPrice)  DESC;");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblReport5.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("name"));
              vect.add(rs.getString("surname"));
              vect.add(rs.getString("SnackName"));
              vect.add(rs.getInt("Quantity"));
              vect.add(rs.getFloat("SUM(Quantity*SnackPrice)"));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void getReport6() throws SQLException{
      ResultSet rs=db.query("SELECT name, surname, SUM(Quantity), AVG(Quantity*SnackPrice) FROM person JOIN customer ON customer.cIDNumber=person.IDNumber JOIN purchase ON customer.cIDNumber=purchase.cIDNumber JOIN snack_purchase ON snack_purchase.PurchaseID=purchase.PurchaseID JOIN snack ON snack.SnackID=snack_purchase.SnackID GROUP BY purchase.cIDNumber ORDER BY AVG(Quantity*SnackPrice) DESC");
      
      ResultSetMetaData rsD =rs.getMetaData();
      
      int colCount;
      colCount=rsD.getColumnCount();
      DefaultTableModel dT=(DefaultTableModel)tblReport6.getModel();
      dT.setRowCount(0);
      while(rs.next()){
          Vector vect=new Vector();
          for(int i=0; i<colCount;i++){
              vect.add(rs.getString("name"));
              vect.add(rs.getString("surname"));
              vect.add(rs.getInt("SUM(Quantity)"));
              vect.add(String.format("%.2f",rs.getFloat("AVG(Quantity*SnackPrice)") ));
            
          }
          
          dT.addRow(vect);
     }
    }
    
    public void generateScript() throws IOException{
        List<Ticket> tList=td.getTicketArray();
        List<Purchase> pList=pd.getPurchArray();
        
        for(Ticket t: tList){
            t.insertStmt();
        }
        
        for(Purchase p: pList){
            p.insertP();
        }
        
    }
    

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCust;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTable tblMovie;
    private javax.swing.JTable tblReport1;
    private javax.swing.JTable tblReport2;
    private javax.swing.JTable tblReport3;
    private javax.swing.JTable tblReport4;
    private javax.swing.JTable tblReport5;
    private javax.swing.JTable tblReport6;
    private javax.swing.JTable tblScreening;
    private javax.swing.JTable tblSnack_purch;
    private javax.swing.JTable tblSnacks;
    private javax.swing.JTable tblTickType;
    private javax.swing.JTable tblTickets;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
